In [1]:
name = "Nimsara"
print("My name is "+name)

My name is Nimsara

In [2]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [3]:
import pandas as pd

In [1]:
print ('Hello, Welcome to your Machine Learning Module')
x = 12
y = 0
z = x + y
print ('adding', x,' to', y, 'is', z)

Hello, Welcome to your Machine Learning Module
adding 12  to 0 is 12

In [2]:
while True:
  print('Forever Loop')

Streaming output truncated to the last 5000 lines.
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop
Forever Loop

KeyboardInterrupt:

Part (C) Data Manipulations in Google Colab

In [4]:
# importing pandas lib
import pandas as pd
# Loading data into a Data frame.
data_frame = pd.read_csv('/content/drive/MyDrive/Colab_Notebooks/Mall_Customers.csv')

In [5]:
# displaying first 5 rows
data_frame.head()

   CustomerID  Gender   Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male  19.0                15.0                     NaN
1           2    Male   NaN                15.0                    81.0
2           3  Female  20.0                16.0                     6.0
3           4  Female  23.0                 NaN                    77.0
4           5  Female   NaN                 NaN                    40.0

In [6]:
# display first 2 rows
data_frame.head(2)

   CustomerID Gender   Age  Annual Income (k$)  Spending Score (1-100)
0           1   Male  19.0                15.0                     NaN
1           2   Male   NaN                15.0                    81.0

In [9]:
# Display last 5 rows
data_frame.tail()

     CustomerID  Gender   Age  Annual Income (k$)  Spending Score (1-100)
195         196  Female  35.0               120.0                    79.0
196         197  Female  45.0               126.0                    28.0
197         198    Male  32.0               126.0                    74.0
198         199    Male  32.0               137.0                    18.0
199         200    Male  30.0               137.0                    83.0

In [10]:
# display last 10 rows
data_frame.tail(10)

     CustomerID  Gender   Age  Annual Income (k$)  Spending Score (1-100)
190         191  Female  34.0               103.0                    23.0
191         192  Female  32.0               103.0                    69.0
192         193    Male  33.0               113.0                     8.0
193         194  Female  38.0               113.0                    91.0
194         195  Female  47.0               120.0                    16.0
195         196  Female  35.0               120.0                    79.0
196         197  Female  45.0               126.0                    28.0
197         198    Male  32.0               126.0                    74.0
198         199    Male  32.0               137.0                    18.0
199         200    Male  30.0               137.0                    83.0

In [11]:
# Print all column names of the data_frame
list(data_frame.columns)

['CustomerID', 'Gender', 'Age', 'Annual Income (k$)', 'Spending Score (1-100)']

In [12]:
list(data_frame.rows)

AttributeError: 'DataFrame' object has no attribute 'rows'

In [13]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     197 non-null    float64
 3   Annual Income (k$)      198 non-null    float64
 4   Spending Score (1-100)  199 non-null    float64
dtypes: float64(3), int64(1), object(1)
memory usage: 7.9+ KB

In [14]:
# output descriptive statistics for numeric data columns
data_frame.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  197.000000          198.000000              199.000000
mean   100.500000   39.000000           61.005051               50.256281
std     57.879185   14.002915           26.017857               25.876350
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   29.000000           42.250000               34.500000
50%    100.500000   36.000000           62.000000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [15]:
# output descriptive statistics to CATEGORICAL (non numeric) data columns.
data_frame.describe(include = 'object')

        Gender
count      200
unique       2
top     Female
freq       112

In [17]:
# to get number of rows and columns
data_frame.shape

(200, 5)

In [19]:
# total number of missing values per column
data_frame.isnull().sum()

CustomerID                0
Gender                    0
Age                       3
Annual Income (k$)        2
Spending Score (1-100)    1
dtype: int64

In [20]:
# percentage of missing values per column
data_frame.isnull().sum()/len(data_frame)*100

CustomerID                0.0
Gender                    0.0
Age                       1.5
Annual Income (k$)        1.0
Spending Score (1-100)    0.5
dtype: float64

In [21]:
# removing rows (rows - Instances. columns - Features)
# using drop(index) function, we can drop a row at a particular index

# row indexing starts at 0, 1, 2, 3,.. etc.

data_frame.drop(4, inplace=True)
data_frame.head()

   CustomerID  Gender   Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male  19.0                15.0                     NaN
1           2    Male   NaN                15.0                    81.0
2           3  Female  20.0                16.0                     6.0
3           4  Female  23.0                 NaN                    77.0
5           6  Female  22.0                17.0                    76.0

In [22]:
# to remove multiple rows, we include a list of indices
# here, row numbers 0, 1 and 2 are removed

data_frame.drop([0, 1, 2], inplace=True)
data_frame.head()

   CustomerID  Gender   Age  Annual Income (k$)  Spending Score (1-100)
3           4  Female  23.0                 NaN                    77.0
5           6  Female  22.0                17.0                    76.0
6           7  Female   NaN                18.0                     6.0
7           8  Female  23.0                18.0                    94.0
8           9    Male  64.0                19.0                     3.0