In [ ]:
print("Hello World, Welcome to your Machine Learning module");

Hello World, Welcome to your Machine Learning module

In [ ]:
print(2-1)

1

In [ ]:
print("My name is Nimsara")

My name is Nimsara

In [ ]:
name = "Nimsara"
print("My name is "+ name)

My name is Nimsara

In [ ]:
print(name+" is my name")

Nimsarais my name

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:
data_frame = pd.read_csv('/content/drive/MyDrive/Mall_Customers.csv')

In [ ]:
data_frame.head()

   CustomerID  Gender   Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male  19.0                15.0                     NaN
1           2    Male   NaN                15.0                    81.0
2           3  Female  20.0                16.0                     6.0
3           4  Female  23.0                 NaN                    77.0
4           5  Female   NaN                 NaN                    40.0

In [ ]:
data_frame.tail

<bound method NDFrame.tail of      CustomerID  Gender   Age  Annual Income (k$)  Spending Score (1-100)
0             1    Male  19.0                15.0                     NaN
1             2    Male   NaN                15.0                    81.0
2             3  Female  20.0                16.0                     6.0
3             4  Female  23.0                 NaN                    77.0
4             5  Female   NaN                 NaN                    40.0
..          ...     ...   ...                 ...                     ...
195         196  Female  35.0               120.0                    79.0
196         197  Female  45.0               126.0                    28.0
197         198    Male  32.0               126.0                    74.0
198         199    Male  32.0               137.0                    18.0
199         200    Male  30.0               137.0                    83.0

[200 rows x 5 columns]>

In [ ]:
data_frame.tail()

     CustomerID  Gender   Age  Annual Income (k$)  Spending Score (1-100)
195         196  Female  35.0               120.0                    79.0
196         197  Female  45.0               126.0                    28.0
197         198    Male  32.0               126.0                    74.0
198         199    Male  32.0               137.0                    18.0
199         200    Male  30.0               137.0                    83.0

In [ ]:
list(data_frame.columns)

['CustomerID', 'Gender', 'Age', 'Annual Income (k$)', 'Spending Score (1-100)']

In [ ]:
data_frame.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 5 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   CustomerID              200 non-null    int64
 1   Gender                  200 non-null    object
 2   Age                     197 non-null    float64
 3   Annual Income (k$)      198 non-null    float64
 4   Spending Score (1-100)  199 non-null    float64
dtypes: float64(3), int64(1), object(1)
memory usage: 7.9+ KB

In [ ]:
data_frame.describe()

       CustomerID         Age  Annual Income (k$)  Spending Score (1-100)
count  200.000000  197.000000          198.000000              199.000000
mean   100.500000   39.000000           61.005051               50.256281
std     57.879185   14.002915           26.017857               25.876350
min      1.000000   18.000000           15.000000                1.000000
25%     50.750000   29.000000           42.250000               34.500000
50%    100.500000   36.000000           62.000000               50.000000
75%    150.250000   49.000000           78.000000               73.000000
max    200.000000   70.000000          137.000000               99.000000

In [ ]:
data_frame.shape

(200, 5)

In [ ]:
data_frame['Age'].describe()

count    197.000000
mean      39.000000
std       14.002915
min       18.000000
25%       29.000000
50%       36.000000
75%       49.000000
max       70.000000
Name: Age, dtype: float64

In [ ]:
data_frame.isnull()

     CustomerID  Gender    Age  Annual Income (k$)  Spending Score (1-100)
0         False   False  False               False                    True
1         False   False   True               False                   False
2         False   False  False               False                   False
3         False   False  False                True                   False
4         False   False   True                True                   False
..          ...     ...    ...                 ...                     ...
195       False   False  False               False                   False
196       False   False  False               False                   False
197       False   False  False               False                   False
198       False   False  False               False                   False
199       False   False  False               False                   False

[200 rows x 5 columns]

In [ ]:
data_frame.isnull().sum()

CustomerID                0
Gender                    0
Age                       3
Annual Income (k$)        2
Spending Score (1-100)    1
dtype: int64

In [ ]:
data_frame.drop(4, inplace=True)

In [ ]:
data_frame.head()

   CustomerID  Gender   Age  Annual Income (k$)  Spending Score (1-100)
0           1    Male  19.0                15.0                     NaN
1           2    Male   NaN                15.0                    81.0
2           3  Female  20.0                16.0                     6.0
3           4  Female  23.0                 NaN                    77.0
5           6  Female  22.0                17.0                    76.0

In [1]:
from google.drive import drive
drive.mount('/content/drive')

ModuleNotFoundError: No module named 'google.drive'